### PR TITLE
Check that fullstory is initialized

### PR DESCRIPTION
**Pull request by igrayson**
This resolves https://github.com/getsentry/sentry-fullstory/issues/55

### CODE REVIEW

**Comment by igrayson** [comment]
Alternate implementation for your consideration: wrap the fullstory API calls in `try catch (error) { /* set event.contexts.fullstory.error = error.message */ }`

**Comment by igrayson** [comment]
@mgaeta ?

**Comment by igrayson** [comment]
@scefali  ?

**Review by scefali — APPROVED** [review]

**Comment by scefali** [comment]
Looks good to me! @leeandher Think you can merge this and make a new release?

**Pull request merged**
